CHANGES.md, lib/search.js
https://treetopllc.jira.com/browse/COL-1811
https://treetopllc.jira.com/browse/API-918
Main: https://github.com/treetopllc/collaboratory-www/pull/844
=> Adding portal search method

CHANGES.md, component.json, lib/graph/Portal.js, lib/graph/mixin.js
https://treetopllc.jira.com/browse/COL-1912
Main: https://github.com/treetopllc/collaboratory-www/pull/880
=> Add portal POST method

CHANGES.md, lib/graph/Vertex.js
https://treetopllc.jira.com/browse/COL-1874
Main: https://github.com/treetopllc/collaboratory-www/pull/901
=> Return success callback on Vertex DELETE

CHANGES.md, component.json, lib/graph/Organization.js
Main: https://github.com/treetopllc/collaboratory-www/pull/912
=> Update publicActivities query params argument

CHANGES.md, component.json, lib/graph/User.js, package.json
Main PR: https://github.com/treetopllc/collaboratory-www/pull/922
=> COL-1671 Member Home: 4 activities displayed for one activity creation effort

CHANGES.md, component.json, lib/graph/Collaboratory.js, lib/graph/Collaboratory/Portal.js, lib/graph/Noblehour/User.js, lib/graph/mixin.js, package.json
https://treetopllc.jira.com/browse/COL-2067
Added collab.portal.collaborators to api
https://github.com/treetopllc/collaboratory-www/pull/979
=> COL-2067 collab portal endpoint

CHANGES.md, component.json, lib/graph/Collaboratory.js, lib/graph/Collaboratory/User.js, package.json
https://treetopllc.jira.com/browse/COL-2075
https://treetopllc.jira.com/browse/API-1592
Main: https://github.com/treetopllc/collaboratory-www/pull/983
=> Update Collab user endpoints

CHANGES.md, component.json, lib/graph/HoursSet.js, lib/graph/Noblehour.js, package.json
for edit hours
https://treetopllc.jira.com/browse/NH-5874
see details here:
https://treetopllc.jira.com/browse/API-1640
main PR:
https://github.com/treetopllc/nobleweb/pull/1481
=> NH-5874 add hoursSets.preview() endpoint

CHANGES.md, component.json, lib/graph/Group.js, package.json
Main PR:
https://github.com/treetopllc/nobleweb/issues/1599
* API-1741
=> NH-6104 Unable to Remove Contributed Opps from Group Home page

CHANGES.md, component.json, lib/graph/Opportunity.js, package.json
main:
https://github.com/treetopllc/nobleweb/pull/1601
others related to this:
https://github.com/treetopllc/crown/pull/112
https://github.com/treetopllc/noble-go-sdk/pull/374
=> NH-6088: add new opp.types endpoint

CHANGES.md, component.json, lib/graph/Collaboratory/User.js, package.json
Main PR:
https://github.com/treetopllc/collaboratory-www/pull/1034
=> COL-1388 Track Dashboard Content Tab

CHANGES.md, component.json, lib/graph/Organization.js, package.json
Main PR:
https://github.com/treetopllc/collaboratory-www/pull/1049
Added new org/:id/groups/detailed endpoint.
=> COL-1290, COL-2264

CHANGES.md, component.json, lib/graph/Organization.js, package.json
required for:
https://github.com/treetopllc/nobleweb/pull/1623
=> NH-6083 add new org.hosts() endpoint

CHANGES.md, component.json, lib/graph/User.js, package.json
Nobleweb PR:
https://github.com/treetopllc/nobleweb/pull/1679
=> NH-6150 Track: Track Hours Opportunity Delete Removes the Opportunity from NobleHour for all Users

CHANGES.md, component.json, lib/graph/Opportunity.js, package.json
https://treetopllc.jira.com/browse/NH-5989
for PR:
=> add new endpoint opp.userAsset

CHANGES.md, component.json, lib/graph/Opportunity.js, package.json
@aprilb when we do a "release" for this I'll create the NH master and feature_opps PRs. Thanks!
=> NH-6287 remove deprecated and bump version

CHANGES.md, component.json, lib/graph/Organization.js, package.json
https://treetopllc.jira.com/browse/NH-6223
updates the location of the org.opportunity endpoint.
main PR:
https://github.com/treetopllc/nobleweb/pull/1766
=> NH-6223 rename endpoint location for organization.opportunities

CHANGES.md, component.json, lib/graph/Invite.js, package.json
Main: https://github.com/treetopllc/collaboratory-www/pull/1164
=> COL-2265 Create Invite to Register Modal view

CHANGES.md, component.json, lib/graph/Organization.js, package.json
https://treetopllc.jira.com/browse/NH-6405
new endpoint to submit an opp for moderation. to be called when creating a new opp (after success) and when patching an opp's host_id.
main PR:
https://github.com/treetopllc/nobleweb/pull/1891
=> add new POST endpoint for submitting an opp to moderation

CHANGES.md, component.json, lib/graph/Collaboratory/Portal.js
Master: https://github.com/treetopllc/collaboratory-www/pull/1304
=> COL-2561 Add Course Code to Add Course Modal

CHANGES.md, component.json, lib/graph/Organization.js, package.json
people really want it to be 2019... I fixed that.
main PR: https://github.com/treetopllc/nobleweb/pull/1996
=> NH-6464 admin reports new endpoints

CHANGES.md, component.json, lib/graph/Group.js, package.json
https://treetopllc.jira.com/browse/NH-6300
add two new Group endpoints for Group reports 
Related PR:
https://github.com/treetopllc/nobleweb/pull/2003
=> NH-6300 Add two new Group endpoints

CHANGES.md, component.json, lib/graph/Opportunity.js, package.json
Implements new opportunity impact endpoint, from https://github.com/treetopllc/gonoble/pull/2171
Required to finish up work on https://treetopllc.jira.com/projects/NH/issues/NH-5954
Wasn't able to find anything about query parameters for this, but I left the `query` arg in - just in case. Should I leave it out?
=> Add opportunity impact endpoint

CHANGES.md, component.json, lib/graph/Opportunity.js, package.json
The new Opportunity Impact endpoint uses the same 'participation' endpoint as Organizations, so I should've just copied that over.
Required for work on https://treetopllc.jira.com/projects/NH/issues/NH-5954
=> Fix opp impact endpoint (use participation)

CHANGES.md, component.json, lib/graph/Collaboratory.js, lib/graph/Collaboratory/Class.js, lib/graph/Collaboratory/Course.js, lib/graph/Collaboratory/Portal.js, lib/graph/Collaboratory/Unit.js, lib/graph/Collaboratory/User.js, package.json
Implemented new Classes/Courses/Units/Portlas/Users endpoints:
- GET: /col/users/:id/classes
- GET: /col/users/:id/classes/public
- GET: /col/classes/:id
- GET: /col/courses/:id
- POST: /col/courses/:course_id/classes
- GET: /col/portals/:portal_id/course_prefixes
- GET: /col/portals/:portal_id/courses
- GET: /col/portals/:portal_id/courses/:course_id/collaborators/with_dupes
- POST: /col/portals/:portal_id/units
- GET: /col/portals/:portal_id/units/:unit_id/related_activities
- GET: /col/units/:id/course_prefixes
- DELETE: /col/units/:id/course_prefixes/:prefix
=> COL-2566 select add class modal

CHANGES.md, component.json, lib/graph/Collaboratory/Unit.js, package.json
Add new `COL_Unit.postCoursePrefix()` endpoint
Required for: https://github.com/treetopllc/collaboratory-www/pull/1325
=> COL-2335 Unit form: Capture and display new unit abbreviation field for course entry

CHANGES.md, component.json, lib/graph/Opportunity.js, package.json
Pretty straightforward, copied from Org relationships.
Currently blocked by small API ticket: https://treetopllc.jira.com/browse/API-2290
Blocks FE work on: https://treetopllc.jira.com/projects/NH/issues/NH-6358
Versioned to 0.12.30, so maybe this should wait to merge after 0.12.29: https://github.com/treetopllc/noble.js/pull/82
=> Add Opportunity relationships endpoint

CHANGES.md, component.json, lib/graph/Collaboratory/Portal.js, package.json
https://treetopllc.jira.com/browse/COL-2080
=> COL-2080 units view courses tab

CHANGES.md, component.json, lib/graph/User.js, package.json, test/lib/graph/User.js
https://treetopllc.jira.com/browse/NH-6654
Clean up User.groups() endpoint
=> NH-6654 clean up user groups

CHANGES.md, component.json, lib/graph/Asset.js, lib/graph/Collaboratory/Portal.js, lib/graph/Vertex.js, lib/lists.js, lib/search.js, lib/utils.js, package.json
Main: https://github.com/treetopllc/collaboratory-www/pull/1392
=> Admin: Add new course/section for admin user COL-2658, COL-2670, COL-2672, COL-2643, COL-2676

CHANGES.md, component.json, lib/graph/Collaboratory/Portal.js, package.json
Main PR:
https://github.com/treetopllc/collaboratory-www/pull/1405
=> COL-2630 Display Section SLO & Pedagogies in Section Modal

CHANGES.md, component.json, lib/graph/Noblehour/Community.js, package.json
Depends on:
https://github.com/treetopllc/nobleweb/pull/2200
=> NH-6819  Add new Moderations Endpoints to Noble.js

CHANGES.md, component.json, lib/graph/Noblehour.js, lib/graph/Noblehour/Community.js, package.json
Fixed some syntax errors, exposed community
Depends on: https://github.com/treetopllc/nobleweb/pull/2208
=> NH-6819 new moderations endpoints

CHANGES.md, component.json, lib/graph/User.js, package.json
Just a little change required for https://github.com/treetopllc/nobleweb/pull/2191
Thanks to @sirbolkins for the solution <3
=> User Network: Forward params as query

CHANGES.md, component.json, lib/graph/User.js, package.json, test/lib/graph/User.js
https://treetopllc.jira.com/browse/NH-6624
Add params to user.roles
Related to PR: https://github.com/treetopllc/nobleweb/pull/2218
=> NH-6624 display left next to opps with accepted hour sets

CHANGES.md, component.json, lib/graph/Noblehour/Community.js, package.json
Main PR: https://github.com/treetopllc/nobleweb/pull/2232
Adds query params to the moderation drilldown endpoints.
=> NH-6811 Moderate Header Vertex Filter

CHANGES.md, component.json, lib/graph/Collaboratory/Portal.js, package.json
https://treetopllc.jira.com/browse/COL-2650
=> COL-2650-noble.js td use new classes collaborators

CHANGES.md, component.json, lib/graph/Collaboratory/Portal.js, package.json
Main:
https://github.com/treetopllc/collaboratory-www/pull/1453
Depends on:
https://github.com/treetopllc/gonoble/pull/2477
https://github.com/treetopllc/gonoble/pull/2476
=> COL-2766 (TD) Remove FE workaround to get section's parent submission status on collaborator's endpoint

CHANGES.md, component.json, lib/graph/Collaboratory/Portal.js, package.json
* Removed deprecated collaborators endpoint
* Added prospective collaborators endpoint
Main: https://github.com/treetopllc/collaboratory-www/pull/1554
=> COL-2812 TD: Migrate Endpoints from Deprecated Portal Collaborators to New Collaborators

CHANGES.md, component.json, lib/graph/Activity.js, package.json
Main: https://github.com/treetopllc/collaboratory-www/pull/1561
=> Updates to Proxy/AL Flows: COL-2847/COL-2848 & COL-2875/COL-2876
